apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
  - image: code-server
    docker:
      dockerfile: Dockerfile
      buildArgs:
        vscodeVersion: 1.41.0
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
